<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GLLive</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
		<style type="text/css">
    	html {
				height: 100%;
      }
      body {
        margin:0px;
        padding:0px;
				overflow: hidden;
				background-color:gray;
      }

			#logo {
				position:absolute;
				left:8px;
				top:8px;
			}
			#viewport {
				margin:0px;
				border:0px;
				padding:0px;
			}
			#progress {
				position:absolute;
				left:0px;
				top:0px;
			  right:0px;
			  bottom:0px;
				margin:auto;
			}
			#progress-bk {
				position:fixed;
    		top:0;
    		bottom:0;
    		left:0;
    		right:0;
    		background:#303030;
			}
			#live {
				position:absolute;
				top:-8px;
			  right:-4px;
				width:100px;
				height:62px;
			}
			.break-news {
				background-color:#303030;
				font-family:"Neue Haas Grotesk";
				font-weight:bold;
			}
			.break-news-panel {
				padding:8px;
			}
			.break-news-content {
				padding:0px;
				background-color:black;
			}
			.break-news-content .jumbotron {
				background-color: #000;
				color:#f15738;
				color:#f6d50e;
			}
			.break-news-content .jumbotron .break-news-cap {
				color:#777;
				color:#a1a1a1;
			}
			.break-news-content .jumbotron .break-news-location {
				font-family:"Neue Haas Grotesk";
				font-weight:bold;
				color:#f3a137;
			}
			.break-news-content .jumbotron .break-news-desc {
				font-family:"Neue Haas Grotesk";
				font-weight:bold;
				color:#777;
			}
			.break-news-content #break-news-n1-pic {
				left:0px;
			  right:0px;
			  bottom:64px;
				margin:auto;
			}
			.panel-feed {
				background:#303030;
				border-color:#444;
				color:#cfcfcf;
			}

			#carousel-globe {
				position:absolute;
				left:0px;
			  right:0px;
			  bottom:0px;
				margin:auto;
				color:white;
				text-align:center;
				font-family:'Neue Haas Grotesk';
				font-size:72px;
				color:#a1a1a1;
			}
		</style>
  </head>
  <body>

		<div id="viewport">
		</div>
		<div id="carousel-globe" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner">
      </div>
    </div>


			  <!--img id="break-news-n1-pic" src="http://s.developers.org.ua/img/announces/420x230_ag420_2.png"></img-->
				  <!--img src="http://www.globallogic.com/wp-content/themes/globallogic/img/logo.png" style="float:right;width:20%;height:20%;"/-->

		<!-- twitter + php
	 	stackoverflow.com/questions/12916539/simplest-php-example-for-retrieving-user-timeline-with-twitter-api-version-1-1/15314662#15314662 -->
				<!--a id="twitter-widget" class="twitter-timeline" href="https://twitter.com/search?q=%23Globallogic" data-widget-id="418408420543184896">#Globallogic</a-->

		<div id="break-news-n1" class="break-news"/>
			<span class="break-news-panel">
				<div class="break-news-content">
				  <h1 id="break-news-n1-title" class="break-news-cap">Apax Partners' Funds to acquire GlobalLogic</h1>
				  <h2 id="break-news-n1-title-location" class="break-news-location">McLean, VA<div  id="break-news-n1-timestamp" class="pull-right">october 8, 2013</div></h2>
					<h3 id="break-news-n1-desc" class="break-news-desc">ODSA Topco Limited ("ODSA"), a company backed by Funds advised by Apax Partners ("Apax"), a global private equity firm, and GlobalLogic, a full-lifecycle product development services company, today announced that they have entered into a definitive agreement for ODSA to acquire GlobalLogic...</h3>
				</div>
			</span>
		</div>
		<!--div id="break-news-n2" class="break-news"/>
			<div class="break-news-content">
				<div class="jumbotron">
				  <h2 id="break-news-n2-title" class="break-news-cap">Welcome to IT Club Mykolaiv</h2>
				  <h3 id="break-news-n2-title-location" class="break-news-location">Mykolaiv, UA<div  id="break-news-n2-timestamp" class="pull-right">december 23, 2013</div></h3>
					<h4 id="break-news-n2-desc" class="break-news-desc">Механізм SEO. Покрокове просування сайту (Олександра Марко), Pragmatic SCRUM (Костянтин Мірін)</h4>
				</div>
			</div>
		</div>
		<div id="break-news-n3" class="break-news"/>
			<div class="break-news-content">
				<div class="panel panel-default panel-feed">
			  	<div class="panel-body">
						<img class="pull-right" src="img/facebook.png"></img>
  				</div>
				</div>
			</div>
		</div>
		<div id="break-news-n4" class="break-news"/>
			<div class="break-news-content">
				<div class="panel panel-default panel-feed">
					<div class="panel-heading" style="background:#303030;border-color:#444;color:#cfcfcf;">#Globallogic<img class="pull-right" src="img/twitter.png"></img></div>
			  	<div class="panel-body">
<p><a href="https://twitter.com/intent/tweet?in_reply_to=51113028241989632">Reply</a></p>
<p><a href="https://twitter.com/intent/retweet?tweet_id=51113028241989632">Retweet</a></p>
<p><a href="https://twitter.com/intent/favorite?tweet_id=51113028241989632">Favorite</a></p>
  				</div>
				</div>
			</div>
		</div-->
		<!-- loading -->
		<!--div id="progress-bk">
			<img id="progress" src="img/loader.gif"/>
		</div-->
		<!-- logos -->
		<!--div>
			<img id="logo" src="img/gl-logo.png"/>
			<img id="live" src="img/live-2.png"/>
		</div-->

  </body>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

	<script src="https://code.jquery.com/jquery.min.js" type="text/javascript"></script>
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="js/bootstrap.min.js"></script>
	<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  <script src="js/three.min.js"></script>
  <script src="js/gl-live.js"></script>
</html>

